name: Run Script

on:
    push:
          branches:
              - main # Change this to your default branch if different

jobs:
    run-script:
          runs-on: ubuntu-latest # Use the latest version of Ubuntu
          steps:
              - name: Checkout Repository
                uses: actions/checkout@v2 # Checks out your repository code

              - name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                      node-version: "14" # Specify the Node.js version

              - name: Install Dependencies
                run: npm install # Install your project's dependencies

              - name: Instal CORS
                run: npm install cors express

              - name: List Files
                run: ls -la

              - name: Run Your Script
                run: node src/server.js # Adjust the path accordingly
