name: Run Script

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change to src directory
        run: cd src  # Change to the directory containing package.json

      - name: Install Dependencies
        run: npm install  # Install your project's dependencies

      - name: Run Your Script
        run: node server.js  # Adjust the path accordingly
